app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from app import ROOMS


class JoinForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    room = StringField('Room', validators=[DataRequired()])
    submit = SubmitField('Join Room')

    def validate_name(self, name):
        if self.room.data in ROOMS:
            if self.name.data in ROOMS[self.room.data].players:
                raise ValidationError('Please user another name.')

    def validate_room(self, room):
        if self.room.data not in ROOMS:
            raise ValidationError('Room does not exist.')

app/room/forms.py
from flask import current_app
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired, URL, NumberRange


class CreateForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    song = StringField('Song', validators=[DataRequired()], id='autocomplete')
    artist = StringField('Artist', validators=[DataRequired()], id='artist')
    duration = IntegerField('Time Limit (mins)', validators=[DataRequired()], description='Time per song')
    submit = SubmitField('Create Room')


class PlaylistForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    playlist = StringField('Spotify Playlist ID', validators=[DataRequired(), URL()])
    duration = IntegerField('Time Limit (mins)', validators=[DataRequired()])
    submit = SubmitField('Create Room')


class FreeForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    number_of_songs = StringField('Number of Songs', validators=[DataRequired(),
                                                                 NumberRange(1, 10)])
    category = SelectField('Category', choices=[])
    duration = IntegerField('Time Limit (mins)', validators=[DataRequired()])
    submit = SubmitField('Create Room')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

from app.spotify.auth import SpotifyCredentials
from app.spotify.spotify import Spotify
from config import Config

socketio = SocketIO()
ROOMS = {}
spotify_auth = SpotifyCredentials()
spotify = Spotify(spotify_auth)


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.room import bp as room_bp
    app.register_blueprint(room_bp)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import session, render_template, url_for, redirect

from app.main.forms import JoinForm
from . import bp


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    form = JoinForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('room.room', room=session.get('room', '')))
    return render_template('index.html', form=form)

app/room/__init__.py
from flask import Blueprint

bp = Blueprint('room', __name__)

from app.room import routes, events

app/room/routes.py
from flask import render_template, session, url_for, redirect, request
from flask.json import jsonify

from app import ROOMS, spotify
from app.game.manager import Manager
from app.room import bp
from app.room.forms import CreateForm


@bp.route('/room/<room>')
def room(room):
    name = session.get('name', '')
    session_room = session.get('room', '')
    if name == '' or session_room == '' or session_room != room or room not in ROOMS:
        return redirect(url_for('main.index'))
    gm = ROOMS[room]
    return render_template('room/room.html', title=room, name=name, song=gm.song.display_name)


@bp.route('/create', methods=['GET', 'POST'])
def create():
    form = CreateForm()
    if form.validate_on_submit():
        gm = Manager(form.song.data, form.artist.data, spotify_manager=spotify, duration=form.duration.data)
        while gm.room_id in ROOMS:
            # Generate new id if id already in manager
            gm.generate_room_id()
        room_id = gm.room_id
        ROOMS[room_id] = gm
        session['name'] = form.name.data
        session['room'] = room_id
        return redirect(url_for('room.room', room=session.get('room', '')))
    return render_template('room/create.html', form=form, title='Create Room')


@bp.route('/song_autocomplete', methods=['GET', 'POST'])
def song_autocomplete():
    search_term = request.args.get('term')
    if not search_term:
        return jsonify([])
    tracks = spotify.search_track(search_term)
    options = [{'value': t['name'],
                'label': t['name'] + ' by ' + t['artists'][0]['name'],
                'artist': t['artists'][0]['name']}
               for t in tracks]
    return jsonify(options)

@bp.route('/playlist_mode', methods=['GET', 'POST'])
def get_playlist():
    return

app/spotify/auth.py
import base64
import json
import os
from datetime import datetime, timedelta

import requests


class SpotifyCredentials(object):
    AUTH_URL = 'https://accounts.spotify.com/api/token'

    def __init__(self, client_id=None, client_secret=None, proxies=None):

        if not client_id:
            client_id = os.environ.get('SPOTIFY_ID')

        if not client_secret:
            client_secret = os.environ.get('SPOTIFY_SECRET')

        if not proxies:
            proxies = {
                "http": os.environ.get('http_proxy'),
                "https": os.environ.get('http_proxy'),
                "no_proxy": os.environ.get('no_proxy'),
            }

        self.client_id = client_id
        self.client_secret = client_secret
        self.proxies = proxies

        self._request_auth_token()

    @property
    def auth_token(self):
        if self._is_token_expired():
            self._request_auth_token()
        return self.auth_details["access_token"]

    def _get_auth_header(self):
        encoded_bytes = base64.urlsafe_b64encode('{}:{}'.format(self.client_id, self.client_secret).encode("utf-8"))
        encoded_str = str(encoded_bytes)
        return {"Authorization": "Basic {}".format(encoded_str)}

    def _request_auth_token(self):
        payload = {'grant_type': 'client_credentials'}
        req_time = datetime.utcnow()
        resp = requests.post('https://accounts.spotify.com/api/token',
                             headers=self._get_auth_header(),
                             data=payload,
                             verify=True,
                             proxies=self.proxies)
        if resp.status_code == 200:
            self.auth_details = json.loads(resp.text)
            self.auth_details['time_requested'] = req_time

    def _is_token_expired(self):
        if not self.auth_details or (datetime.utcnow() - self.auth_details['time_requested']) >=\
                timedelta(seconds=self.auth_details['expires_in']):
            return True
        return False

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    Guess The Song{% if title %} - {{ title }}{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Guess The Song</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if song %}
                    <li><a href="#" onclick="leave_room();">Leave Room</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    {% block footer %}
    <footer class="footer">
        <div class="container text-center">
            <span class="text-muted">Created by: Woodenpuppy</span>
        </div>
    </footer>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}"/>
    {% endblock %}

    <div class="container text-center">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Join Room</h1>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <br>
    <p><a href="{{ url_for('room.create') }}">Create Room</a></p>
{% endblock %}

app/templates/room/create.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles -%}
{{super()}}
    <link href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.css" rel="stylesheet"/>
{% endblock styles %}

{% block app_content %}
        <h1>Create</h1>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
{% endblock %}

{% block scripts %}
{{super()}}
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.js"></script>
<script>
$(function() {
$('#autocomplete').autocomplete({
    source: function( request, response ) {
        $.ajax( {
          url: "{{ url_for('room.song_autocomplete') }}"+"?term="+request.term,
          success: function( data ) {
            response( data );
          }
        } );
        },
    minLength: 2,
    select: function(event, ui) {
        $('#artist').val(ui.item.artist)
    }
    });
});
</script>
{% endblock %}

app/templates/room/room.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
        <div class="container jumbotron text-center">
            <h1 id="song" class="jumbotron-heading"></h1>
            <p id="time" class="lead text-muted"></p>
        </div>
        <div class="container">
            <div class="row">
                <div id="clues"></div>
                <div class="col-sm-3 col-md-offset-1">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                        <h5 class="card-title">Latest Guesses</h5>
                        </div>
                        <ul id="latest_guesses" class="list-group list-group-flush"></ul>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-offset-2">
                  <textarea id="chat" class="form-control" readonly style="height: 250px;"></textarea>
                </div>
            </div>
        </div>
        <hr>
        <div class="container">
            <div class="input-group col-sm-6 col-md-offset-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Make A Guess</span>
              </div>
              <input id="text" size="80" placeholder="Enter Guess Here" type="text" class="form-control">
            </div>
        </div>
        <br>
        <br>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/room.js') }}"></script>
{{super()}}
{% endblock %}